### ISSUE TITLE
Bug: `push_task` failure uses uninitialized worker.logger

### ISSUE THREAD

**Issue by dhkron** [Intsights/sergeant#24]
`push_task` method can fail when redis/mongo are not available. In that case, `self.logger.exception` is invoked - self being a worker instance.
However, the `push_task` caller should not assume that worker.logger is initialized, nor exists.
If that's a requirement from each `Worker` implementation, it should be enforced in code.

Exception example -  `sergeant/worker.py in push_task at line 157`
```python
...
                consumable_from=consumable_from,
            )
            return True
        except Exception as exception:
            self.logger.error(
                msg=f'could not push task: {exception}',
            )
            return False
...
```

**Comment by wavenator** [comment]
Fixed on master. Will be released in the next version.
