### ISSUE TITLE
When using Redis connector, tasks are sporadically crashing\failing.

### ISSUE THREAD

**Issue by liorbunzl** [Intsights/sergeant#39]
* To reproduce, just create a worker configured to redis, and add a few tasks.
* See similar issue here: https://github.com/andymccurdy/redis-py/issues/1426

Description:
According to the above issue, the problem seems to be because the redis connector is using single_connection_client, which is not thread safe. 
As it is currently defined, it is generating the redis object with single_connection_client flag on.

```
      class Connector(
          _connector.Connector,
      ):
          name: str = 'redis'
      
      def __init__(
          self,
          nodes: typing.List[typing.Dict[str, typing.Any]],
      ) -> None:
          self.connections = [
              QueueRedis(
                  host=node['host'],
                  port=node['port'],
                  password=node['password'],
                  db=node['database'],
                  retry_on_timeout=True,
                  socket_keepalive=True,
                  socket_connect_timeout=10,
                  socket_timeout=60,
                  single_connection_client=True,
              )
```

That caused the CI of the agent to sporadically fail when testing integration push (which is using sergeant.worker), but only after adding a second task.

**Comment by wavenator** [comment]
A great catch! Fixed in version `v0.22.0`.

Thanks for the report
