### ISSUE TITLE
Default logs are not proper English.

### ISSUE THREAD

**Issue by alon710** [Intsights/sergeant#5]
The built-in logs should start with an upper case letter and end with a ".".
few examples I found:

Files with bad logs that I found:
- https://github.com/Intsights/sergeant/blob/f94539e96b204aff2391f0fd1589f5322ab1f103/sergeant/worker.py
- https://github.com/Intsights/sergeant/blob/f94539e96b204aff2391f0fd1589f5322ab1f103/sergeant/executor/threaded.py

Examples:

"task has retried" --> "Task has retried."
"worker is starving" --> "Worker is starving."

**Comment by wavenator** [comment]
The issue was discussed face to face. Log messages should not be capitalized as they are not meant to be read by a human being.
